name: flutter_ui_component
description: A Flutter package providing reusable UI components inspired by Uber Base Design System
version: 1.0.0
homepage: https://github.com/your-org/flutter_ui_component

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  json_dynamic_widget: ^10.0.2
  json_class: ^3.0.1
  json_theme: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  golden_toolkit: ^0.15.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
